In [1]:
from mplsoccer import Sbopen
import pandas as pd

parser = Sbopen()

In [2]:
competitions = parser.competition()
competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [3]:
wc = competitions[
(competitions["competition_name"]=="FIFA World Cup") &
(competitions['season_name'].isin(['2018','2022']))
]
wc

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
29,43,106,International,FIFA World Cup,male,False,True,2022,2024-12-16T10:15:11.055845,2024-12-16T10:21:13.710934,2024-12-16T10:21:13.710934,2024-12-16T10:15:11.055845
30,43,3,International,FIFA World Cup,male,False,True,2018,2024-06-12T07:38:19.345758,2021-06-13T16:17:31.694,None,2024-06-12T07:38:19.345758

In [4]:
all_matches=[]
all_shots=[]

In [5]:
for _, tournament in wc.iterrows():

    competition_id = tournament['competition_id']
    season_id = tournament['season_id']

    print(f"Loading season: {tournament['season_name']}")

    matches = parser.match(
        competition_id=competition_id,
        season_id=season_id
    )

    all_matches.append(matches)

    for match_id in matches['match_id']:

        try:
            events, related, freeze, tactics = parser.event(match_id)

            shots = events[
                events['type_name'] == 'Shot'
            ].copy()

            shots['season_name'] = tournament['season_name']

            all_shots.append(shots)

        except Exception as e:
            print(f"Error in match {match_id}: {e}")

Loading season: 2022
Loading season: 2018

In [6]:
shots_df = pd.concat(all_shots, ignore_index=True)

In [7]:
shots_df.shape

(3200, 89)

In [10]:
shots_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 89 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              3200 non-null   object
 1   index                           3200 non-null   int64
 2   period                          3200 non-null   int64
 3   timestamp                       3200 non-null   object
 4   minute                          3200 non-null   int64
 5   second                          3200 non-null   int64
 6   possession                      3200 non-null   int64
 7   duration                        3200 non-null   float64
 8   match_id                        3200 non-null   int64
 9   type_id                         3200 non-null   int64
 10  type_name                       3200 non-null   object
 11  possession_team_id              3200 non-null   int64
 12  possession_team_name            3200 non-null   object
 13  play_pattern_id                 3200 non-null   int64
 14  play_pattern_name               3200 non-null   object
 15  team_id                         3200 non-null   int64
 16  team_name                       3200 non-null   object
 17  tactics_formation               0 non-null      object
 18  player_id                       3200 non-null   float64
 19  player_name                     3200 non-null   object
 20  position_id                     3200 non-null   float64
 21  position_name                   3200 non-null   object
 22  pass_recipient_id               0 non-null      float64
 23  pass_recipient_name             0 non-null      object
 24  pass_length                     0 non-null      float64
 25  pass_angle                      0 non-null      float64
 26  pass_height_id                  0 non-null      float64
 27  pass_height_name                0 non-null      object
 28  end_x                           3200 non-null   float64
 29  end_y                           3200 non-null   float64
 30  body_part_id                    3200 non-null   float64
 31  body_part_name                  3200 non-null   object
 32  sub_type_id                     3200 non-null   float64
 33  sub_type_name                   3200 non-null   object
 34  x                               3200 non-null   float64
 35  y                               3200 non-null   float64
 36  pass_cross                      0 non-null      object
 37  outcome_id                      3200 non-null   float64
 38  outcome_name                    3200 non-null   object
 39  under_pressure                  567 non-null    float64
 40  shot_statsbomb_xg               3200 non-null   float64
 41  technique_id                    3200 non-null   float64
 42  technique_name                  3200 non-null   object
 43  shot_first_time                 825 non-null    object
 44  goalkeeper_position_id          0 non-null      float64
 45  goalkeeper_position_name        0 non-null      object
 46  pass_assisted_shot_id           0 non-null      object
 47  pass_shot_assist                0 non-null      object
 48  end_z                           2150 non-null   float64
 49  shot_key_pass_id                2219 non-null   object
 50  off_camera                      0 non-null      float64
 51  pass_deflected                  0 non-null      object
 52  counterpress                    0 non-null      float64
 53  aerial_won                      253 non-null    object
 54  pass_switch                     0 non-null      object
 55  out                             38 non-null     float64
 56  foul_won_defensive              0 non-null      object
 57  shot_one_on_one                 140 non-null    object
 58  pass_cut_back                   0 non-null      object
 59  block_offensive                 0 non-null      object
 60  foul_committed_card_id          0 non-null      float64
 61  foul_committed_card_name        0 non-null      object
 62  pass_goal_assist                0 non-null      object
 63  shot_deflected                  39 non-null     object
 64  block_deflection                0 non-null      object
 65  foul_committed_advantage        0 non-null      object
 66  foul_won_advantage              0 non-null      object
 67  pass_miscommunication           0 non-null      object
 68  ball_recovery_recovery_failure  0 non-null      object
 69  dribble_nutmeg                  0 non-null      object
 70  shot_open_goal                  30 non-null     object
 71  substitution_replacement_id     0 non-null      float64
 72  substitution_replacement_name   0 non-null      object
 73  injury_stoppage_in_chain        0 non-null      object
 74  bad_behaviour_card_id           0 non-null      float64
 75  bad_behaviour_card_name         0 non-null      object
 76  season_name                     3200 non-null   object
 77  pass_no_touch                   0 non-null      object
 78  dribble_overrun                 0 non-null      object
 79  foul_committed_offensive        0 non-null      object
 80  ball_recovery_offensive         0 non-null      object
 81  foul_committed_penalty          0 non-null      object
 82  foul_won_penalty                0 non-null      object
 83  dribble_no_touch                0 non-null      object
 84  shot_follows_dribble            5 non-null      object
 85  block_save_block                0 non-null      object
 86  half_start_late_video_start     0 non-null      object
 87  shot_redirect                   8 non-null      object
 88  pass_backheel                   0 non-null      object
dtypes: float64(25), int64(10), object(54)
memory usage: 2.2+ MB

In [9]:
wc[['competition_name', 'season_name']]

   competition_name season_name
29   FIFA World Cup        2022
30   FIFA World Cup        2018

In [11]:
shots_df.to_csv(
    "../data/raw/world_cup_shots.csv",
    index=False
)