In [1]:
from mplsoccer import Sbopen
import pandas as pd

parser = Sbopen()

In [2]:
competitions = parser.competition()
competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,None,None,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,None,None,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,None,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,None,2024-02-13T02:35:28.134882

In [3]:
wc = competitions[
(competitions["competition_name"]=="FIFA World Cup") &
(competitions['season_name'].isin(['2018','2022']))
]
wc

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
29,43,106,International,FIFA World Cup,male,False,True,2022,2024-12-16T10:15:11.055845,2024-12-16T10:21:13.710934,2024-12-16T10:21:13.710934,2024-12-16T10:15:11.055845
30,43,3,International,FIFA World Cup,male,False,True,2018,2024-06-12T07:38:19.345758,2021-06-13T16:17:31.694,None,2024-06-12T07:38:19.345758

In [4]:
all_matches=[]
all_shots=[]

In [ ]:
for _, tournament in wc.iterrows():

    competition_id = tournament['competition_id']
    season_id = tournament['season_id']

    print(f"Loading season: {tournament['season_name']}")

    matches = parser.match(
        competition_id=competition_id,
        season_id=season_id
    )

    all_matches.append(matches)

    for match_id in matches['match_id']:

        try:
            events, related, freeze, tactics = parser.event(match_id)

            shots = events[
                events['type_name'] == 'Shot'
            ].copy()

            shots['season_name'] = tournament['season_name']

            all_shots.append(shots)

        except Exception as e:
            print(f"Error in match {match_id}: {e}")

Loading season: 2022
Loading season: 2018

In [ ]:
shots_df = pd.concat(all_shots, ignore_index=True)

In [ ]:
shots_df.shape

In [ ]:
shots_df.info()

In [ ]:
wc[['competition_name', 'season_name']]