In [1]:
import pandas as pd  
import  numpy as np

In [2]:
shots = pd.read_csv('../data/raw/world_cup_shots.csv')
shots

,id,index,period,timestamp,minute,second,possession,duration,match_id,type_id,...,foul_committed_offensive,ball_recovery_offensive,foul_committed_penalty,foul_won_penalty,dribble_no_touch,shot_follows_dribble,block_save_block,half_start_late_video_start,shot_redirect,pass_backheel
0,61d52e72-a8ff-49c4-be02-057b1ea0fb15,20,1,00:00:18.696000,0,18,2,0.380264,3857256,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aa77495b-0e7b-44f0-a2eb-11605085943a,25,1,00:00:22.129000,0,22,2,0.175803,3857256,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51026369-a4ad-4a71-b14a-6e7f8b764772,28,1,00:00:23.845000,0,23,2,0.495575,3857256,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6ac240f5-8b84-4c06-8153-b56109c8c5e6,196,1,00:04:35.297000,4,35,11,0.848375,3857256,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00e599c0-5234-4b6a-9b91-d6f789a311b0,356,1,00:10:05.636000,10,5,24,0.934407,3857256,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,6f238f72-f4b1-4f33-8c35-3a867f6e4e63,3142,2,00:31:09.880000,76,9,128,1.053000,7559,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3196,0ca9d191-7abc-472e-bcfa-532d5ccc36f8,3223,2,00:35:04.120000,80,4,132,0.560000,7559,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3197,5ce39d13-e290-428b-844e-c0a611a0035a,3237,2,00:35:57.280000,80,57,133,0.973000,7559,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3198,5394cab7-ad64-45da-9e7c-df7669414773,3617,2,00:45:30.240000,90,30,153,0.440000,7559,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3199,84855116-f3ee-4671-b757-b9ce80d79008,3827,2,00:49:05.160000,94,5,158,0.893000,7559,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
shots.shape

(3200, 89)

In [4]:
shots.columns.tolist()

['id',
 'index',
 'period',
 'timestamp',
 'minute',
 'second',
 'possession',
 'duration',
 'match_id',
 'type_id',
 'type_name',
 'possession_team_id',
 'possession_team_name',
 'play_pattern_id',
 'play_pattern_name',
 'team_id',
 'team_name',
 'tactics_formation',
 'player_id',
 'player_name',
 'position_id',
 'position_name',
 'pass_recipient_id',
 'pass_recipient_name',
 'pass_length',
 'pass_angle',
 'pass_height_id',
 'pass_height_name',
 'end_x',
 'end_y',
 'body_part_id',
 'body_part_name',
 'sub_type_id',
 'sub_type_name',
 'x',
 'y',
 'pass_cross',
 'outcome_id',
 'outcome_name',
 'under_pressure',
 'shot_statsbomb_xg',
 'technique_id',
 'technique_name',
 'shot_first_time',
 'goalkeeper_position_id',
 'goalkeeper_position_name',
 'pass_assisted_shot_id',
 'pass_shot_assist',
 'end_z',
 'shot_key_pass_id',
 'off_camera',
 'pass_deflected',
 'counterpress',
 'aerial_won',
 'pass_switch',
 'out',
 'foul_won_defensive',
 'shot_one_on_one',
 'pass_cut_back',
 'block_offensive',
 'foul_committed_card_id',
 'foul_committed_card_name',
 'pass_goal_assist',
 'shot_deflected',
 'block_deflection',
 'foul_committed_advantage',
 'foul_won_advantage',
 'pass_miscommunication',
 'ball_recovery_recovery_failure',
 'dribble_nutmeg',
 'shot_open_goal',
 'substitution_replacement_id',
 'substitution_replacement_name',
 'injury_stoppage_in_chain',
 'bad_behaviour_card_id',
 'bad_behaviour_card_name',
 'season_name',
 'pass_no_touch',
 'dribble_overrun',
 'foul_committed_offensive',
 'ball_recovery_offensive',
 'foul_committed_penalty',
 'foul_won_penalty',
 'dribble_no_touch',
 'shot_follows_dribble',
 'block_save_block',
 'half_start_late_video_start',
 'shot_redirect',
 'pass_backheel']

In [5]:
shots.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 89 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              3200 non-null   object
 1   index                           3200 non-null   int64
 2   period                          3200 non-null   int64
 3   timestamp                       3200 non-null   object
 4   minute                          3200 non-null   int64
 5   second                          3200 non-null   int64
 6   possession                      3200 non-null   int64
 7   duration                        3200 non-null   float64
 8   match_id                        3200 non-null   int64
 9   type_id                         3200 non-null   int64
 10  type_name                       3200 non-null   object
 11  possession_team_id              3200 non-null   int64
 12  possession_team_name            3200 non-null   object
 13  play_pattern_id                 3200 non-null   int64
 14  play_pattern_name               3200 non-null   object
 15  team_id                         3200 non-null   int64
 16  team_name                       3200 non-null   object
 17  tactics_formation               0 non-null      float64
 18  player_id                       3200 non-null   float64
 19  player_name                     3200 non-null   object
 20  position_id                     3200 non-null   float64
 21  position_name                   3200 non-null   object
 22  pass_recipient_id               0 non-null      float64
 23  pass_recipient_name             0 non-null      float64
 24  pass_length                     0 non-null      float64
 25  pass_angle                      0 non-null      float64
 26  pass_height_id                  0 non-null      float64
 27  pass_height_name                0 non-null      float64
 28  end_x                           3200 non-null   float64
 29  end_y                           3200 non-null   float64
 30  body_part_id                    3200 non-null   float64
 31  body_part_name                  3200 non-null   object
 32  sub_type_id                     3200 non-null   float64
 33  sub_type_name                   3200 non-null   object
 34  x                               3200 non-null   float64
 35  y                               3200 non-null   float64
 36  pass_cross                      0 non-null      float64
 37  outcome_id                      3200 non-null   float64
 38  outcome_name                    3200 non-null   object
 39  under_pressure                  567 non-null    float64
 40  shot_statsbomb_xg               3200 non-null   float64
 41  technique_id                    3200 non-null   float64
 42  technique_name                  3200 non-null   object
 43  shot_first_time                 825 non-null    object
 44  goalkeeper_position_id          0 non-null      float64
 45  goalkeeper_position_name        0 non-null      float64
 46  pass_assisted_shot_id           0 non-null      float64
 47  pass_shot_assist                0 non-null      float64
 48  end_z                           2150 non-null   float64
 49  shot_key_pass_id                2219 non-null   object
 50  off_camera                      0 non-null      float64
 51  pass_deflected                  0 non-null      float64
 52  counterpress                    0 non-null      float64
 53  aerial_won                      253 non-null    object
 54  pass_switch                     0 non-null      float64
 55  out                             38 non-null     float64
 56  foul_won_defensive              0 non-null      float64
 57  shot_one_on_one                 140 non-null    object
 58  pass_cut_back                   0 non-null      float64
 59  block_offensive                 0 non-null      float64
 60  foul_committed_card_id          0 non-null      float64
 61  foul_committed_card_name        0 non-null      float64
 62  pass_goal_assist                0 non-null      float64
 63  shot_deflected                  39 non-null     object
 64  block_deflection                0 non-null      float64
 65  foul_committed_advantage        0 non-null      float64
 66  foul_won_advantage              0 non-null      float64
 67  pass_miscommunication           0 non-null      float64
 68  ball_recovery_recovery_failure  0 non-null      float64
 69  dribble_nutmeg                  0 non-null      float64
 70  shot_open_goal                  30 non-null     object
 71  substitution_replacement_id     0 non-null      float64
 72  substitution_replacement_name   0 non-null      float64
 73  injury_stoppage_in_chain        0 non-null      float64
 74  bad_behaviour_card_id           0 non-null      float64
 75  bad_behaviour_card_name         0 non-null      float64
 76  season_name                     3200 non-null   int64
 77  pass_no_touch                   0 non-null      float64
 78  dribble_overrun                 0 non-null      float64
 79  foul_committed_offensive        0 non-null      float64
 80  ball_recovery_offensive         0 non-null      float64
 81  foul_committed_penalty          0 non-null      float64
 82  foul_won_penalty                0 non-null      float64
 83  dribble_no_touch                0 non-null      float64
 84  shot_follows_dribble            5 non-null      object
 85  block_save_block                0 non-null      float64
 86  half_start_late_video_start     0 non-null      float64
 87  shot_redirect                   8 non-null      object
 88  pass_backheel                   0 non-null      float64
dtypes: float64(58), int64(11), object(20)
memory usage: 2.2+ MB

In [6]:
selected_features = [
    'minute',
    'second',
    'period',
    'team_name',
    'player_name',
    'position_name',
    'x',
    'y',
    'end_x',
    'end_y',
    'body_part_name',
    'technique_name',
    'play_pattern_name',
    'under_pressure',
    'shot_first_time',
    'shot_one_on_one',
    'shot_open_goal',
    'shot_deflected',
    'shot_statsbomb_xg',
    'outcome_name',
    'season_name'
]
selected_features

['minute',
 'second',
 'period',
 'team_name',
 'player_name',
 'position_name',
 'x',
 'y',
 'end_x',
 'end_y',
 'body_part_name',
 'technique_name',
 'play_pattern_name',
 'under_pressure',
 'shot_first_time',
 'shot_one_on_one',
 'shot_open_goal',
 'shot_deflected',
 'shot_statsbomb_xg',
 'outcome_name',
 'season_name']

In [7]:
# creating a clean dataframe
df =  shots[selected_features].copy()
df

,minute,second,period,team_name,player_name,position_name,x,y,end_x,end_y,...,technique_name,play_pattern_name,under_pressure,shot_first_time,shot_one_on_one,shot_open_goal,shot_deflected,shot_statsbomb_xg,outcome_name,season_name
0,0,18,1,Switzerland,Granit Xhaka,Left Defensive Midfield,96.0,38.8,108.2,38.5,...,Half Volley,From Kick Off,NaN,True,NaN,NaN,NaN,0.036566,Blocked,2022
1,0,22,1,Switzerland,Breel-Donald Embolo,Center Forward,113.1,40.7,114.8,40.6,...,Half Volley,From Kick Off,NaN,True,NaN,NaN,NaN,0.353289,Saved,2022
2,0,23,1,Switzerland,Granit Xhaka,Left Defensive Midfield,103.8,41.9,115.5,39.1,...,Half Volley,From Kick Off,NaN,True,NaN,NaN,NaN,0.069527,Saved,2022
3,4,35,1,Serbia,Nikola Milenković,Right Center Back,112.2,36.8,120.0,35.3,...,Normal,From Corner,NaN,NaN,NaN,NaN,NaN,0.081609,Off T,2022
4,10,5,1,Serbia,Andrija Živković,Right Wing Back,97.8,51.5,120.0,36.1,...,Normal,Regular Play,NaN,NaN,NaN,NaN,NaN,0.030002,Post,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3195,76,9,2,Egypt,Amr Medhat Warda,Center Attacking Midfield,102.0,22.0,112.0,36.0,...,Normal,From Goal Kick,NaN,NaN,NaN,NaN,NaN,0.028970,Blocked,2018
3196,80,4,2,Saudi Arabia,Mohammed Al Burayk,Right Back,95.0,30.0,104.0,32.0,...,Normal,From Free Kick,NaN,NaN,NaN,NaN,NaN,0.065623,Blocked,2018
3197,80,57,2,Saudi Arabia,Salem Mohammed Al Dawsari,Center Attacking Midfield,116.0,30.0,119.0,36.8,...,Volley,From Throw In,NaN,True,NaN,NaN,NaN,0.088908,Saved,2018
3198,90,30,2,Saudi Arabia,Abdullah Ibrahim Otayf,Center Defensive Midfield,101.0,58.0,106.0,52.0,...,Normal,Regular Play,1.0,NaN,NaN,NaN,NaN,0.020325,Blocked,2018
3199,94,5,2,Saudi Arabia,Salem Mohammed Al Dawsari,Center Attacking Midfield,116.0,53.0,120.0,36.4,...,Half Volley,Regular Play,NaN,True,NaN,NaN,NaN,0.021029,Goal,2018

In [8]:
df['goal'] = np.where(
    df['outcome_name'] == 'Goal',
    1,
    0
)

In [9]:
# fill missing columns
boolean_cols = [
    'under_pressure',
    'shot_first_time',
    'shot_one_on_one',
    'shot_open_goal',
    'shot_deflected'
]

for col in boolean_cols:
    df[col] = df[col].fillna(False).astype(bool)

C:\Users\joshi\AppData\Local\Temp\ipykernel_25032\3745295251.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)
C:\Users\joshi\AppData\Local\Temp\ipykernel_25032\3745295251.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)
C:\Users\joshi\AppData\Local\Temp\ipykernel_25032\3745295251.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)
C:\Users\joshi\AppData\Local\Temp\ipykernel_25032\3745295251.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)

In [10]:
df[boolean_cols].dtypes

under_pressure     bool
shot_first_time    bool
shot_one_on_one    bool
shot_open_goal     bool
shot_deflected     bool
dtype: object

In [11]:
df.isnull().sum()

minute               0
second               0
period               0
team_name            0
player_name          0
position_name        0
x                    0
y                    0
end_x                0
end_y                0
body_part_name       0
technique_name       0
play_pattern_name    0
under_pressure       0
shot_first_time      0
shot_one_on_one      0
shot_open_goal       0
shot_deflected       0
shot_statsbomb_xg    0
outcome_name         0
season_name          0
goal                 0
dtype: int64

In [12]:
df['goal'].value_counts()

goal
0    2822
1     378
Name: count, dtype: int64

In [13]:
df.head()

,minute,second,period,team_name,player_name,position_name,x,y,end_x,end_y,...,play_pattern_name,under_pressure,shot_first_time,shot_one_on_one,shot_open_goal,shot_deflected,shot_statsbomb_xg,outcome_name,season_name,goal
0,0,18,1,Switzerland,Granit Xhaka,Left Defensive Midfield,96.0,38.8,108.2,38.5,...,From Kick Off,False,True,False,False,False,0.036566,Blocked,2022,0
1,0,22,1,Switzerland,Breel-Donald Embolo,Center Forward,113.1,40.7,114.8,40.6,...,From Kick Off,False,True,False,False,False,0.353289,Saved,2022,0
2,0,23,1,Switzerland,Granit Xhaka,Left Defensive Midfield,103.8,41.9,115.5,39.1,...,From Kick Off,False,True,False,False,False,0.069527,Saved,2022,0
3,4,35,1,Serbia,Nikola Milenković,Right Center Back,112.2,36.8,120.0,35.3,...,From Corner,False,False,False,False,False,0.081609,Off T,2022,0
4,10,5,1,Serbia,Andrija Živković,Right Wing Back,97.8,51.5,120.0,36.1,...,Regular Play,False,False,False,False,False,0.030002,Post,2022,0

In [14]:
df.to_csv(
    "../data/processed/cleaned_shots.csv",
    index=False
)