In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(
    "../data/processed/cleaned_shots.csv"
)

df.head()

,match_id,competition_name,season_name,minute,second,period,team,player,position,shot_body_part,...,shot_one_on_one,shot_open_goal,shot_deflected,shot_statsbomb_xg,shot_outcome,x,y,end_x,end_y,goal
0,3923881,African Cup of Nations,2023,3,36,1,Côte d'Ivoire,Sébastien Haller,Center Forward,Head,...,0,0,0,0.077357,Wayward,106.7,42.1,115.6,48.4,0
1,3923881,African Cup of Nations,2023,6,10,1,Côte d'Ivoire,Sébastien Haller,Center Forward,Right Foot,...,0,0,0,0.187051,Off T,109.1,35.5,120.0,46.6,0
2,3923881,African Cup of Nations,2023,7,8,1,Côte d'Ivoire,Simon Adingra,Left Wing,Right Foot,...,0,0,0,0.013922,Off T,113.6,23.8,120.0,45.7,0
3,3923881,African Cup of Nations,2023,13,4,1,Côte d'Ivoire,Seko Fofana,Left Center Midfield,Right Foot,...,0,0,0,0.027030,Saved,91.8,40.2,118.1,40.2,0
4,3923881,African Cup of Nations,2023,20,1,1,Côte d'Ivoire,Obite Evan Ndicka,Left Center Back,Head,...,0,0,0,0.030268,Wayward,111.0,31.3,113.6,34.4,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7863 entries, 0 to 7862
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           7863 non-null   int64
 1   competition_name   7863 non-null   object
 2   season_name        7863 non-null   int64
 3   minute             7863 non-null   int64
 4   second             7863 non-null   int64
 5   period             7863 non-null   int64
 6   team               7863 non-null   object
 7   player             7863 non-null   object
 8   position           7863 non-null   object
 9   shot_body_part     7863 non-null   object
 10  shot_technique     7863 non-null   object
 11  play_pattern       7863 non-null   object
 12  under_pressure     7863 non-null   int64
 13  shot_first_time    7863 non-null   int64
 14  shot_one_on_one    7863 non-null   int64
 15  shot_open_goal     7863 non-null   int64
 16  shot_deflected     7863 non-null   int64
 17  shot_statsbomb_xg  7863 non-null   float64
 18  shot_outcome       7863 non-null   object
 19  x                  7863 non-null   float64
 20  y                  7863 non-null   float64
 21  end_x              7863 non-null   float64
 22  end_y              7863 non-null   float64
 23  goal               7863 non-null   int64
dtypes: float64(5), int64(11), object(8)
memory usage: 1.4+ MB

In [3]:
df.isnull().sum()

match_id             0
competition_name     0
season_name          0
minute               0
second               0
period               0
team                 0
player               0
position             0
shot_body_part       0
shot_technique       0
play_pattern         0
under_pressure       0
shot_first_time      0
shot_one_on_one      0
shot_open_goal       0
shot_deflected       0
shot_statsbomb_xg    0
shot_outcome         0
x                    0
y                    0
end_x                0
end_y                0
goal                 0
dtype: int64

In [4]:
df["goal"].value_counts(normalize=True)

goal
0    0.883887
1    0.116113
Name: proportion, dtype: float64

In [5]:
df[["x", "y", "end_x", "end_y"]].describe()

                 x            y        end_x        end_y
count  7863.000000  7863.000000  7863.000000  7863.000000
mean    104.087638    39.813328   115.525932    40.053084
std       8.686645     9.720966     6.654137     6.966178
min      30.200000     0.700000    66.500000     0.100000
25%      98.000000    33.000000   113.000000    36.400000
50%     105.900000    40.000000   119.000000    40.000000
75%     110.900000    46.700000   120.000000    44.000000
max     120.100000    79.300000   120.000000    80.000000

In [6]:
df = df[
    (df["x"] >= 0) &
    (df["x"] <= 120) &
    (df["y"] >= 0) &
    (df["y"] <= 80)
]

In [7]:
df = df.reset_index(drop=True)

In [8]:
print(df.shape)

(7862, 24)

In [9]:
df["goal"].value_counts()

goal
0    6949
1     913
Name: count, dtype: int64

In [10]:
df.isnull().sum()

match_id             0
competition_name     0
season_name          0
minute               0
second               0
period               0
team                 0
player               0
position             0
shot_body_part       0
shot_technique       0
play_pattern         0
under_pressure       0
shot_first_time      0
shot_one_on_one      0
shot_open_goal       0
shot_deflected       0
shot_statsbomb_xg    0
shot_outcome         0
x                    0
y                    0
end_x                0
end_y                0
goal                 0
dtype: int64

In [11]:
df["shot_outcome"].value_counts()

shot_outcome
Off T               2506
Blocked             2061
Saved               1706
Goal                 913
Wayward              485
Post                 154
Saved to Post         23
Saved Off Target      14
Name: count, dtype: int64

In [12]:
df.head()

,match_id,competition_name,season_name,minute,second,period,team,player,position,shot_body_part,...,shot_one_on_one,shot_open_goal,shot_deflected,shot_statsbomb_xg,shot_outcome,x,y,end_x,end_y,goal
0,3923881,African Cup of Nations,2023,3,36,1,Côte d'Ivoire,Sébastien Haller,Center Forward,Head,...,0,0,0,0.077357,Wayward,106.7,42.1,115.6,48.4,0
1,3923881,African Cup of Nations,2023,6,10,1,Côte d'Ivoire,Sébastien Haller,Center Forward,Right Foot,...,0,0,0,0.187051,Off T,109.1,35.5,120.0,46.6,0
2,3923881,African Cup of Nations,2023,7,8,1,Côte d'Ivoire,Simon Adingra,Left Wing,Right Foot,...,0,0,0,0.013922,Off T,113.6,23.8,120.0,45.7,0
3,3923881,African Cup of Nations,2023,13,4,1,Côte d'Ivoire,Seko Fofana,Left Center Midfield,Right Foot,...,0,0,0,0.027030,Saved,91.8,40.2,118.1,40.2,0
4,3923881,African Cup of Nations,2023,20,1,1,Côte d'Ivoire,Obite Evan Ndicka,Left Center Back,Head,...,0,0,0,0.030268,Wayward,111.0,31.3,113.6,34.4,0

In [13]:
df.to_csv(
    "../data/processed/cleaned_shots.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.